language: ruby
rvm:
  - 2.1.2
install:
  - bundle install
after_success:
  - CI=true TRAVIS=true coveralls --verbose
notifications:
  email:
    recipients:
      - icaro.seara@email.com
    on_failure: change
    on_success: never