language: ruby
rvm:
  - 2.1.2
script: 'bundle exec rspec'
notifications:
  email:
    recipients:
      - icaro.seara@email.com
    on_failure: change
    on_success: never
addons:
  code_climate:
    repo_token: adf08323